apiVersion: v1
kind: Service
metadata:
  name: mlflow-server-svc
  labels:
    app: mlflow-server-svc
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: mlflow-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mlflow-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mlflow-server
        version: v0.2.1
    spec:
      containers:
      - name: "mlflow-server"
        image: "quay.io/zmhassan/mlflow:0.2.1"
        ports:
        - containerPort: 5000
